modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/KessokuTeaTime/ZoomerLibrary/issues"
license = "MIT"

[[mods]]
modId = "zoomerlibrary"
version = "${version}"
displayName = "ZoomerLibrary"
displayURL = "https://github.com/KessokuTeaTime/ZoomerLibrary"
authors = "ThinkingStudio, TexTrue"
credits = "Ennui Langeweile"
description = '''
LibZoomer unofficial Architectury port.

A library that allows for easy and powerful zooming.
'''
logoFile = "icon.png"

[[dependencies.zoomerlibrary]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zoomerlibrary]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zoomerlibrary]]
modId = "architectury"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
