modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"

[[mods]]
modId = "zoomerlibrary"
version = "${version}"
displayName = "ZoomerLibrary"
displayURL="https://github.com/ThinkingStudios/ZoomerLibrary" #optional
logoFile="icon.png" #optional
credits="Ennui Langeweile" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
LibZoomer unofficial forge port.

A library that allows for easy and powerful zooming.
'''

[[dependencies.zoomerlibrary]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zoomerlibrary]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.2]"
ordering = "NONE"
side = "BOTH"
