modLoader = "javafml"
loaderVersion = "[44,)"
license = "MIT"

[[mods]]
modId = "zoomerlibrary_test"
version = "${version}"
displayName = "ZoomerLibraryTest"
displayURL="https://github.com/ThinkingStudios/ZoomerLibrary" #optional
logoFile="icon.png" #optional
credits="Ennui Langeweile" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
LibZoomer unofficial forge port.

A library that allows for easy and powerful zooming.
'''

[[dependencies.zoomerlibrary_test]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zoomerlibrary_test]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.19.4]"
ordering = "NONE"
side = "BOTH"

[[dependencies.zoomerlibrary_test]]
modId = "zoomerlibrary"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"
